version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=gmugrader


  web:
    build: .
    command: sh ./dockerfiles/run_server.sh
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db

