version: "3"
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#db:
#    image: postgres
#    environment:
#      - POSTGRES_USER=abc
#      - POSTGRES_PASSWORD=123

#- POSTGRES_DB=gmugrader


  web:
    build: .
    command: sh ./dockerfiles/run_server.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
